# docker-compose.yml
version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: ${DATABASE}
    ports:
      - "${MONGO_PORT}:27017" # Expõe a porta do host definida em .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db # Para persistência de dados

  api:
    build:
      context: .
      dockerfile: Dockerfile # Veja o exemplo abaixo
    container_name: api
    ports:
      - "${PORT}:3333" # Mapeia a porta da API para o host
    environment:
      # Usa o nome do serviço 'mongo' como host de conexão
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DATABASE: ${DATABASE}
      PORT: ${PORT}
    depends_on:
      - mongo # Garante que o Mongo suba antes da API
    volumes:
      - .:/usr/src/app # Monta seu código dentro do container
      - /usr/src/app/node_modules # Evita sobrescrever node_modules do container

volumes:
  mongo-data:
